### PR TITLE
Migration to mysqli

### PR DESCRIPTION
**Pull request by diego-XA**
This should fix [issue #55](https://github.com/RandomStorm/DVWA/issues/55)

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
Thanks for the pull request! Has this been tested?

**Comment by diego-XA** [comment]
It is not fully tested. It would be good to have some people testing, just in case. 

A month ago I exec a mysql-to-mysqli migration tool command in my installation and then I could install DVWA. Although I did not fully tested everything.

With this PR I executed the very same command in the repository so it should work, although I did not tested an installation from this new repository. 

Anyway the application is broken right now as it dont even install due the mysql connector deprecation in favor of mysqli almost 3 years ago.

**Comment by bradyemerson** [comment]
mysql_result is still present and needs to be updated

**Comment by diego-XA** [comment]
This seems to be a known problem of the conversion tool I used: https://github.com/philip/MySQLConverterTool/issues/9

I see 2 options here:

   1. Slow but elegant: Check the specific cases of the mysql_result ocurrence and fix them accordingly to the case.

    2. Quick but not elegant:  Declare the function posted in the link above and replace all ocurrences of mysql_result with mysqli_result.

**Comment by digininja** [comment]
Got some fixes, any idea how I submit these patches to this pull request?

**Comment by ethicalhack3r** [comment]
I think you're probably best forking DVWA, merging this pull request, implementing your changes, then creating a new pull request. Let me know if I can help!

**Comment by ethicalhack3r** [comment]
I'd delete your current fork repo which is at https://github.com/digininja/DVWA.git
Then re-fork this repo (https://github.com/RandomStorm/DVWA.git).

The above can all be done from the Github web gui. You will now have forked the latest code.

Then to merge this pull request with your fork:

```
git clone https://github.com/digininja/DVWA.git
git checkout -b diego-XA-master master
git pull https://github.com/diego-XA/DVWA.git master
git checkout master
git merge --no-ff diego-XA-master
```

Make your changes.

Then push them back to your forked repo.

```git push origin master``` 

Then click the create pull request button from the Github UI.

**Comment by digininja** [comment]
Something in that lot lost my user so it asks me to login but doesn't
accept my creds. Any ideas?

**Comment by ethicalhack3r** [comment]
If its the issue I think it is, in your cloned directory on your machine:

```vim .git/config ```

Ensure the 'url' parameter has your username in the URL, like the one below:

```url = https://ethicalhack3r@github.com/wpscanteam/wpscan.git```

**Pull request merged**
