### PR TITLE
DVWA v1.9

### PR DESCRIPTION
**Pull request by g0tmi1k**
Before its merged, what else would be required to release the next stable version? =).

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Might be spelling grammar mistakes in: 

+ 847b4ef9c945a983bf6d26e2cf35980649e0855b
+ d41ae43d18aa0eb128ca324f8ebd4e2a9ff210ae

**Comment by g0tmi1k** [comment]
Only things I had left on my to-do list:

+ CSS fixes (however my Web UI skills suck)
+ Mystery level/module (I can think of two nice vectors - missing one)
+ Adding in @digininja websocket // SocketToMe project (I can't come up with enough of an idea for 3x vuln levels)

**Comment by ethicalhack3r** [comment]
:+1: 

Will pull and check grammar then tag

**Comment by g0tmi1k** [comment]
WOOOOOHOOOOO! :cookie: :sunglasses: :birthday: !

**Comment by erwanlr** [comment]
Woot woot, thanks for all those PR :)

**Comment by g0tmi1k** [comment]
Not a problem!
Was fun doing it ;)

**Pull request merged**
