### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by g0tmi1k**
Should fix various issues with DVWA v1.9.

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Please leave open for the time being =).
**Possibly more to come**.

**Comment by ethicalhack3r** [comment]
OK to merge?

**Comment by g0tmi1k** [comment]
Not yet - still slowly going through everything.
Testing every level, every page - making sure stuff is working as designed =).
Will hola once its done.

**Comment by ethicalhack3r** [comment]
Cool, thought I'd check in case you were waiting on me :)

**Comment by g0tmi1k** [comment]
No no!
Sorry dev has slown down - other stuff came up.
Will make loud noises once its 'ready' in my eyes.

**Comment by g0tmi1k** [comment]
Finished!
Don't think there's any more.

+ Tested all levels (Low, Medium, High, Impossible) - all should work as designed
+ Tested all vulnerable levels (Low, Medium, High) - all are possible.
+ Tested impossible levels - at this time, cannot think of a way to abuse it too much.

**Comment by ethicalhack3r** [comment]
Awesome! :+1:

**Comment by g0tmi1k** [comment]
:white_check_mark: :relaxed:

**Pull request merged**
